### ISSUE TITLE
Annual Report

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/board_meetings#10]
I purchased a really nice indesign template and i've been working on a trifold brochure for thunder plains - so we can promote techlahoma and share the good stuff that we do for the community. if anyone wants to give some feedback on data used in the brochure (like "yes, include 2014 data" or "no, use 2015 data only", etc) - that'd be very much appreciated too.

**Comment by the-simian** [comment]
Quick update: we've been using xero and spotlight lately
