### ISSUE TITLE
Invite another Tulsa group leader to January meeting?

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/board_meetings#22]
Can we invite another Tulsa tech community leader to the January meeting? I added a bunch of 200 OK organizers to the Slack team, but I'd like to get more Tulsa perspective into the meetings - I don't feel like I can adequately represent everything that's going on in Tulsa tech community.

**Comment by amandaharlin** [comment]
That sounds great! Please invite people so we can better discuss Tulsa's
perspective. :-) It'll be http://talky.io/techlahoma for the online link
and http://meetup.com/Techlahoma-Foundation for meetup event reminders.
(I'll figure out potential 2016 meeting dates, post it in slack, and then
make meetup events.)

**Comment by the-simian** [comment]
I agree, its good you're attending, but we do need more Tulsa representation

**Comment by groovecoder** [comment]
Hmm ... yeah, when is the January board meeting?

**Comment by amandaharlin** [comment]
haven't made the dayes yet but I was going to ask about 3rd Tuesday
availability

**Comment by groovecoder** [comment]
3rd Tuesday works for me.

**Comment by groovecoder** [comment]
Here are people I'm thinking about inviting to Techlahoma board meetings, and to potentially nominate as board members:
- [Scott Phillips](https://twitter.com/SSADMA) has - at various times - organized Tulsa Web Devs, 200 OK, Ignite Tulsa, Tulsa Startup Weekend, Code for Tulsa, and now Civic Ninjas groups and events
- [John Dungan](https://github.com/jdungan/) has run Tulsa Hack Night and is a Code for Tulsa captain
- [Carlos Moreno](https://twitter.com/chimchim237) is the other Code for Tulsa captain and originator of the fledgling Red Dirt Web Designers group
- [Drew Robinson](https://twitter.com/FatCatArtist) runs the OK Coders Tulsa classes
- [Jason Knight](https://twitter.com/jasontknight) runs Tulsa Agile Practicioners

**Comment by groovecoder** [comment]
I should also point out group leaders that do not interact much with the TWD ecosystem:
- [Sean Whitesell](http://www.meetup.com/TulsaDevelopers-net/members/131644352/) runs the Tulsa .NET Meetup
- [Andrew Chandler](https://plus.google.com/+AndrewChandler-1) runs the Tulsa Java group

**Comment by the-simian** [comment]
Awesome, this is all really good Info. I appreciate these handy lists you're assembling in the various issues

**Comment by groovecoder** [comment]
I invited all these people and Sabrina Gelbart who is wanting to start a Muskogee Web Dev & Design group.

**Comment by amandaharlin** [comment]
Ben of the Tulsa Data Science group just joined our meetup! I sent him a
message saying thanks for joining and that we'd love to talk more.
