### ISSUE TITLE
List Tulsa groups/meetups that could become part of Techlahoma

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/board_meetings#27]

**Comment by groovecoder** [comment]
Most active:
- [Tulsa Web Devs](http://tulsawebdevs.org/)
- [Code for Tulsa](http://codefortulsa.org/)
- [Tulsa Agile Practicioners](http://www.meetup.com/TulsaAgilePractitioners/)

Also around:
- [Tulsa WordPress](http://www.meetup.com/Tulsa-WordPress-meetup/)
- [Oklahoma PHP (Tulsa Chapter)](http://www.meetup.com/OklahomaPHP/)
- [Tulsa Lambda Lounge](https://www.facebook.com/groups/tulsalambdalounge/)
- [Tulsa Data Science Meetup](http://www.meetup.com/Tulsa-Data-Science-Meetup/)
- [Tulsa Java](http://tulsajava.com/)
- [Tulsa .NET Developers](http://tulsadevelopers.net/)

**Comment by rhoegg** [comment]
No tie-in with the TechFest folks?

**Comment by groovecoder** [comment]
That was part of NEOTech - so mostly driven by the Tulsa .NET Developers group.

**Comment by the-simian** [comment]
Perfect, thank you

**Comment by groovecoder** [comment]
So, with this list, how should we invite them? Should I make an email introduction between the group leaders and ... who, exactly?

**Comment by the-simian** [comment]
I was thinking could make an introduction between the officers here and the respective leaders. One email per leader, so if they want to quick-reply they can without entangling everything. Mention our mission/ why we are in alignment with what they are doing at the usergroup level. Then I was thinking of sharing the meetup, slack and github sites with them so they have access to our conversation, projects and meetings. 

Invite them right away to slack, so they can talk to us anytime...
Then invite them to the next meeting, so they can see and engage for themselves.

**Comment by groovecoder** [comment]
Do we have our board@techlahoma.org and/or officers@techlahoma.org email aliases set up yet?

**Comment by amandaharlin** [comment]
I can do that 👍

**Comment by amandaharlin** [comment]
so i'll need everyone to accept a gmail confirmation email asking for forwarding permission. right now i've got forwarding permission for vance, jeremy, jesse, ryan and myself. 

invited today: @groovecoder @matthewreily @DevinClark. need a good email for lucas watson. i don't think tommy will necessarily want to have forwarded email, but we should ask anyway.

**Comment by groovecoder** [comment]
Tulsa Web Devs & Code for Tulsa are in. Tulsa Java and Tulsa Open Source Hardware have applied and we are voting on them at December meeting.

Tulsa Lambda Lounge, Tulsa WordPress, and Tulsa PHP currently meet up at Tulsa Web Devs meetings, so they're kinda-sorta in Techlahoma already, though I can ask them if they want to make it more official.

I've asked Tulsa Data Science and Tulsa .NET leaders about Techlahoma, but we don't have a lot of value to add to their existing groups? Or does someone have a good testimonial of an existing group that joined and the tangible value they got from joining?

In any case, this is an old issue and we have a user group process now (thanks to the awesome @seejessicacode), so I'm closing this. I'll continue to advocate for Tulsa groups to join via the user group process.
