### ISSUE TITLE
Techlahoma Usergroup Definition Proposal

### ISSUE THREAD

**Issue by the-simian** [techlahoma/board_meetings#29]
1. you get to use, and are expected to use techlahoma branding, in turn we have  aresponsibilityt o help promote and mention your group in our own media outlets
   1. there is an understanding that you group is in alignment with our own mission
   2. you are willing to help promote groups other than your own
   3. your group is focused on the betterment of the attendees, the 'users' of your usergroup
   4. You agree to the terms of our CoC
   5. you are willing to allow some time at the beginning of your meeting to allow sponsors to speak (and in turn this is how we can help support you financially)
   6. your status can be revoked by a 75% majority board vote, or on grounds of you violating the Coc or not aligning with the mission. In turn, you reserve the right to walk away any time from the arranagement, if you feel on your end our missions are not in alignment

**Comment by rhoegg** [comment]
Approved by unanimous vote

**Comment by groovecoder** [comment]
:+1:
