### ISSUE TITLE
Closes Meetings Open Spaces

### ISSUE THREAD

**Issue by the-simian** [techlahoma/board_meetings#30]
Reason: Board meetings are currently dual purpose, for community engagement and administration concerns. They are getting longer and harder to weild. Proposal is to separate these into two separate concerns: Town Hall and Board Meetings
1. Close board meetings to special invitation, board members, officers, advisors.
   -Board meetings are monthly
2. Start Town Hall in the style of open spaces.
3. These are quarterly, and follow the style of open spaces
   http://www.amazon.com/Open-Space-Technology-Users-Guide/dp/1576754766

Proposal is to do the first Town Hall in mid April.

**Comment by groovecoder** [comment]
:heart: this

**Comment by rhoegg** [comment]
Approved by unanimous vote.

**Comment by seejessicacode** [comment]
I nominate closing this issue because the motion was approved.

**Comment by the-simian** [comment]
ah thanks, yes this is closed
