### ISSUE TITLE
Software Governance Policy

### ISSUE THREAD

**Issue by jagthedrummer** [techlahoma/board_meetings#35]
# Techlahoma Software Lifecycle and Governance
## Software Developed and Maintained by Techlahoma

The board may vote to officially support the development and maintenance of various software projects. For each project maintained by Techlahoma, the board will recognize a project lead from among the volunteers for the project, and optionally additional developers who will be responsible for development and maintenance of the software. These individuals will also be responsible for addressing / managing reported issues for their sponsored project.

If at any time the board cannot find volunteers to maintain a project, they should take steps to recruit a maintainer, allocate funds to hire a contractor to maintain the project, or they may vote to close the project.
## Software Deployed and Supported by Techlahoma

For all software projects deployed and maintained by Techlahoma, the board will vote annually to continue investing in them, or expire the project. The purpose of this review is to ensure that neglected and unused projects do not continue running, costing money, and possibly exposing vulnerabilities.

For projects deployed and maintained by Techlahoma, the board will recognize a deployment lead from among the volunteers for the project, and optionally additional developers who will be responsible for maintenance, security, appropriate content, and error awareness of the deployment. 

If at any time the board cannot find volunteers to maintain a deployment, they should take steps to recruit a maintainer, allocate funds to hire a contractor to maintain the project, or they may vote to close the project and/or find a 3rd party service as a replacement.

When considering projects for deployment and support by Techlahoma volunteers, the board should take into consideration the criticality of that piece of infrastructure and how that relates to the nature of volunteer work. By relying on volunteers to maintain and support live software deployments, the board acknowledges that the volunteers will often have other responsibilities that may preclude them from responding to incidents as quickly as might be expected from a 3rd party vendor. The more contributors per project the better.
## Hosting and Vendors

To address the security and accessibility of Techlahoma projects, each project should default to being deployed to heroku, github pages, or S3. The board should vote when a project needs to go to a vps/server or other deployment service and make sure a plan is in place with regards to the monitoring, security, key management, and accessibility of that infrastructure.
## Existing Software Projects:
- techlahoma.org
- us.techlahoma.org (blog roll, etc)
- donate.techlahoma.org
- php job board ???

Individual user group sites/projects are not automatically considered as officially supported by Techlahoma itself. The board may vote to assume responsibility for any such projects at their discretion.

**Comment by jagthedrummer** [comment]
Approved by the board on March 25, 2016

**Comment by the-simian** [comment]
approved we should move to wiki
