### ISSUE TITLE
Change access on this repo

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/board_meetings#41]
Right now this repo is controlled by the "Core Owners" team of the Techlahoma GitHub org. We should change it to the Board of Directors team?

**Comment by DevinClark** [comment]
I think we should.

**Comment by DevinClark** [comment]
@groovecoder I made the change. Now we just need to get the newly voted in members on that team.

**Comment by DevinClark** [comment]
Reopen if this isn't completely done. :)

**Comment by the-simian** [comment]
Yep this should be open to the whole board, glad that's fixed
