### ISSUE TITLE
Get hours estimate from everyone involved in 2016

### ISSUE THREAD

**Issue by the-simian** [techlahoma/board_meetings#42]

**Comment by matthewreily** [comment]
4 hours a week on average for me.

**Comment by robolucas** [comment]
About 2 hours for me - more if you count user group attendance, but that's also work for me so it's hard to say. If we count that too it's more like 4.

**Comment by rhoegg** [comment]
Call it 4/week

**Comment by the-simian** [comment]
I'd definitely count usergroup attendance like if you're running the group of course

**Comment by groovecoder** [comment]
3.14159 hours per week.

**Comment by DevinClark** [comment]
3 hours per week.

**Comment by jagthedrummer** [comment]
It fluctuated quite a lot for me over the year. When I was pushing hard on the donations site it was probably 12 hours a week for a few weeks, and then it's settled down to around 2 hours a week. Probably averages out to around 3 or 4 per week.

**Comment by the-simian** [comment]
@jagthedrummer yeah that seems about right. I figured most folks would be averaging big fluctuate-y hours like that. I'm in a similar boat

**Comment by vlucas** [comment]
I'd say it's about 2 hours a week right now, but when the job board stuff was going it was like 10-12. I do have some updates for the job board planned soon, so my number will be lifting up again here in a month or so.

**Comment by amandaharlin** [comment]
hey @vlucas do you want to update your weekly avg numbers? i'd include tp, okcjs, board meeting prep, and job board too.
