### ISSUE TITLE
Estimated Weekly Volunteer Hours for 2017 Board

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/board_meetings#53]
Hey y'all, it's tax time again 💸 That means we need an average of how many hours you spent each week doing work for your position in Techlahoma throughout 2017. Reminder: this only applies to folks who officially served on the board or as officers in 2017.

Please estimate the amount of time you devoted to your position each week and post it in here by Monday, March 19, 2018. If you have questions hmu here/slack or ask Vance.

-------

CC: @vlucas @DevinClark @jagthedrummer @groovecoder @blazedd @the-simian @seejessicacode @amandaharlin @robolucas @tk2u @TRozzell @dustincurzon @aestus @matthewreily

**Comment by amandaharlin** [comment]
If you need an example of what we're filling out, here is a screenshot from our 2016 taxes

<img width="919" alt="screen shot 2018-03-05 at 1 03 42 pm" src="https://user-images.githubusercontent.com/716644/36994132-be4d69c4-2075-11e8-8e3c-36f978e39b6f.png">


And here is a little more info from the IRS' [website, pg 28,](https://www.irs.gov/pub/irs-pdf/i990.pdf) on what we need:

> Column (B). For each person listed in column (A), estimate the
> average hours per week devoted to the organization during the
> year. Entry of a specific number is required for a complete
> answer. Enter “-0-” if applicable. Don't include statements such
> as “as needed,” “as required,” or “40+”. If the average is less
> than one hour per week, then the organization can enter a
> decimal rounded to the nearest tenth (for example, 0.2 hours per
> week).
> For each person listed in column (A), list below the dotted line
> an estimate of the average hours per week (if any) devoted to
> related organizations.

**Comment by DevinClark** [comment]
5 hours a week

**Comment by seejessicacode** [comment]
15 hours a week

**Comment by dustincurzon** [comment]
2 hours

**Comment by vlucas** [comment]
4 hours a week

**Comment by the-simian** [comment]
14 again

**Comment by groovecoder** [comment]
5 per week

**Comment by jagthedrummer** [comment]
Prolly around 3.5/week again for me

**Comment by vlucas** [comment]
Updated mine from 10 down to 4 because I realized this was talking about 2017 :)

**Comment by kendallwerts** [comment]
@DevinClark this is needed for tax purposes. Do you think we should assume 0 for everyone else?

**Comment by kendallwerts** [comment]
I will bring it up at the next board meeting

**Comment by kendallwerts** [comment]
Still need an average number of hours spent on Techlahoma per week in 2017 from @amandaharlin @blazedd @robolucas @tk2u @TRozzell @aestus (Is this Tommy?) and @matthewreily.

This is for tax purposes. Let me know if you have any questions, thanks!!

**Comment by tk2u** [comment]
I spent an average of 2 hours per week in my position in 2017.

**Comment by amandaharlin** [comment]
@kendallcorner 10 hours/week. (and thanks for getting this completed!!)
