### ISSUE TITLE
October Board Minutes - Link to User Group Report

### ISSUE THREAD

**Issue by energydev** [techlahoma/board_meetings#56]
The below link to the User Group Report, from the October Board minutes, appears to be a dead link.

https://github.com/techlahoma/board_meetings/blob/master/2018/committee_reports/10_ug_comm.md

**Comment by kacollins** [comment]
Need to delete this line: https://github.com/techlahoma/board_meetings/blame/master/2018/10_october_minutes.md#L51

**Comment by kacollins** [comment]
Fixed in #57
