### ISSUE TITLE
2023/2024 notes

### ISSUE THREAD

**Issue by geekthattweaks** [techlahoma/board_meetings#93]
Will the 2023/2024 notes be added here or are they hosted somewhere else?

**Comment by kacollins** [comment]
There's a link to them at the bottom of techlahoma.org: https://drive.google.com/drive/folders/1d_TIZlNlXToORQxu6fj_v6QPuJFFrHTf?usp=share_link

**Comment by geekthattweaks** [comment]
Thanks Kimberly! Do you think a PR would get merged if those were added?

**Comment by kacollins** [comment]
@jsonthebson would be a better person to ask, but it doesn't seem like the plan is to maintain this repo.

**Comment by geekthattweaks** [comment]
That is a shame.

Thanks for the help!

**Comment by jsonthebson** [comment]
Thanks for checking @geekthattweaks ! I (Emily) don't use GH super often, and I have to be able to update things. Hope we can have more pushes to here in the future, but not in the current plan for 2024/2025.
